# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatsId', models.CharField(blank=True, max_length=200)),
                ('beatsName', models.CharField(blank=True, max_length=400)),
                ('beatsPincode', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chowki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chowkiId', models.CharField(blank=True, max_length=200)),
                ('chowkiName', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Hulkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hulkasId', models.CharField(blank=True, max_length=200)),
                ('hulkasName', models.CharField(blank=True, max_length=400)),
                ('chowki', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Chowki')),
            ],
        ),
        migrations.CreateModel(
            name='Informer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('beats', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Beats')),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanaId', models.CharField(blank=True, max_length=200)),
                ('thanaName', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='chowki',
            name='thana',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Thana'),
        ),
        migrations.AddField(
            model_name='beats',
            name='hulkas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Hulkas'),
        ),
    ]
